# Generated by Django 2.0 on 2023-07-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('Email', models.EmailField(default='', error_messages={'unique': 'A user with that email already exists.'}, max_length=50, unique=True)),
                ('Password', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
