# Generated by Django 2.0 on 2023-07-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_auto_20230718_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='User',
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
