# Generated by Django 2.0 on 2023-07-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0003_auto_20230718_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
