# Generated by Django 2.0 on 2023-07-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0004_sections_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='Home/uploads/products'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='Home/uploads/sections'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='SectionName',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
