# Generated by Django 2.0 on 2023-07-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0005_auto_20230718_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='Img',
        ),
    ]
