# Generated by Django 2.0.2 on 2023-07-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0007_auto_20230719_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='Pictures/'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='Pictures/'),
        ),
    ]
