# Generated by Django 2.1 on 2023-08-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0012_auto_20230720_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
