# Generated by Django 2.1 on 2023-08-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0013_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
