# Generated by Django 2.1 on 2023-08-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0014_auto_20230817_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='Pictures1/'),
        ),
    ]
