# Generated by Django 2.1 on 2023-08-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0015_auto_20230817_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Ep_Date',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Mf_Date',
        ),
    ]
