# Generated by Django 2.1 on 2023-08-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0016_auto_20230817_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Ep_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Mf_Date',
            field=models.DateField(null=True),
        ),
    ]
