# Generated by Django 2.1 on 2023-08-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0017_auto_20230817_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
