# Generated by Django 2.1 on 2023-08-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0018_products_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='removed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='removed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='removed',
            field=models.BooleanField(default=True),
        ),
    ]
