# Generated by Django 2.1 on 2023-08-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0019_auto_20230817_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sections',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
