# Generated by Django 2.1 on 2023-08-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0020_auto_20230817_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='removed',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
