# Generated by Django 2.1 on 2023-08-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0021_auto_20230817_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groceries.sections'),
        ),
    ]
