# Generated by Django 2.1 on 2023-09-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0027_auto_20230908_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Netprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='Priceperun',
            field=models.IntegerField(default=0),
        ),
    ]
