# Generated by Django 2.1 on 2023-09-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0030_products_qt'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sections',
            table='music_album',
        ),
    ]
